# Generated by Django 5.2.3 on 2025-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_redirecionado', models.URLField()),
                ('link_encurtado', models.CharField()),
            ],
        ),
    ]
