# Generated by Django 5.2.3 on 2025-07-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_original', models.URLField()),
                ('link_encurtado', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='links',
            old_name='link_redirecionado',
            new_name='url_original',
        ),
        migrations.RemoveField(
            model_name='links',
            name='link_encurtado',
        ),
        migrations.AddField(
            model_name='links',
            name='url_encurtado',
            field=models.CharField(default='temp123', max_length=20),
            preserve_default=False,
        ),
    ]
