# Generated by Django 5.2.3 on 2025-07-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_rename_link_redirecionado_links_url_original_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='links',
        ),
    ]
