# Generated by Django 5.2.3 on 2025-07-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_encurtado',
            new_name='url_encurtado',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_original',
            new_name='url_original',
        ),
    ]
